//go:build recall_corpus

// Embedding-recall measurement — the head-to-head counterpart of the
// symbolic-Jaccard calibration sweep (TestRecallMadlibs_CorpusCalibration).
//
// The C.6 Jaccard sweep showed symbolic recall collapsing to ~10% under
// synonym drift. This file scores the SAME 152-topic corpus and the
// SAME depth-stratified query sets with cosine similarity over
// `nomicai-embed` vectors, so the two matrices are directly comparable.
//
// Vectors come from embeddings.json (generated by `make
// recall-embed-data` → test/tools/embed_corpus.py); absent → skip.
// Build-tag isolated (recall_corpus); run via `make recall-corpus-test`.

package scenarios

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"personant/internal/metrics"
)

var embeddingsPath = filepath.Join("testdata", "recall_madlibs", "embeddings.json")

// embedThresholds are the cosine cutoffs swept for the embedding
// matrix. nomic cosines sit on a ~0.4 floor with related text well
// above; the sweep brackets that band.
var embedThresholds = []float64{0.45, 0.50, 0.55, 0.60, 0.65}

type embeddingsDoc struct {
	Model   string               `json:"model"`
	Dim     int                  `json:"dim"`
	Topics  map[string][]float64 `json:"topics"`
	Queries map[string][]float64 `json:"queries"`
}

func loadEmbeddings(t *testing.T) embeddingsDoc {
	t.Helper()
	body, err := os.ReadFile(embeddingsPath)
	if os.IsNotExist(err) {
		t.Skipf("embeddings artifact %s absent — run `make recall-embed-data`", embeddingsPath)
	}
	if err != nil {
		t.Fatalf("read %s: %v", embeddingsPath, err)
	}
	var doc embeddingsDoc
	if err := json.Unmarshal(body, &doc); err != nil {
		t.Fatalf("parse %s: %v", embeddingsPath, err)
	}
	if len(doc.Topics) == 0 || len(doc.Queries) == 0 {
		t.Fatalf("%s: empty topics or queries", embeddingsPath)
	}
	return doc
}

// cosine is the similarity of two embedding vectors. embed_corpus.py
// stores L2-normalized vectors, so cosine is a plain dot product.
func cosine(a, b []float64) float64 {
	var s float64
	for i := range a {
		s += a[i] * b[i]
	}
	return s
}

// embedQueryKey mirrors embed_corpus.py's query keying: the user_input
// with the mad-libs '#' hashtag markers stripped.
func embedQueryKey(userInput string) string {
	return strings.ReplaceAll(userInput, "#", "")
}

// TestRecallMadlibs_EmbedCalibration sweeps synonym-depth M × cosine
// threshold for embedding recall, producing a metrics matrix in the
// same shape as the symbolic-Jaccard one. Per query: cosine the query
// vector against all 152 topic vectors, take topics at or above the
// threshold (top-10 cap, matching the symbolic recall limit), score
// with recallFidelity. Asserts nothing — it is the measurement.
func TestRecallMadlibs_EmbedCalibration(t *testing.T) {
	emb := loadEmbeddings(t)

	type topicVec struct {
		name string
		vec  []float64
	}
	topics := make([]topicVec, 0, len(emb.Topics))
	for name, v := range emb.Topics {
		topics = append(topics, topicVec{name, v})
	}
	sort.Slice(topics, func(i, j int) bool { return topics[i].name < topics[j].name })

	run := metrics.New(map[string]string{
		"measurement": "recall-fidelity-embedding",
		"model":       emb.Model,
	})
	results := map[int]map[float64]calibCell{}

	for _, m := range calibDepths {
		path := filepath.Join("testdata", "recall_madlibs",
			fmt.Sprintf("corpus_queries_m%d.json", m))
		doc := loadMadlibsQueries(t, path)
		results[m] = map[float64]calibCell{}

		for _, th := range embedThresholds {
			var sumP, sumR, sumF float64
			n := 0
			for _, q := range doc.Queries {
				qv, ok := emb.Queries[embedQueryKey(q.UserInput)]
				if !ok {
					t.Errorf("query %s: no embedding (regenerate embeddings.json)", q.ID)
					continue
				}
				type scored struct {
					name string
					cos  float64
				}
				ranked := make([]scored, 0, len(topics))
				for _, tv := range topics {
					ranked = append(ranked, scored{tv.name, cosine(qv, tv.vec)})
				}
				sort.Slice(ranked, func(i, j int) bool { return ranked[i].cos > ranked[j].cos })

				actual := make([]string, 0, 10)
				for _, s := range ranked {
					if s.cos < th || len(actual) >= 10 {
						break
					}
					actual = append(actual, s.name)
				}
				p, r, f := recallFidelity([]string{q.Topic}, actual)
				sumP, sumR, sumF = sumP+p, sumR+r, sumF+f
				n++
			}
			if n == 0 {
				t.Fatalf("depth %d: no queries", m)
			}
			c := calibCell{sumP / float64(n), sumR / float64(n), sumF / float64(n)}
			results[m][th] = c
			tk := int(th*100 + 0.5)
			run.Set(fmt.Sprintf("recall_embed_m%d_t%d_precision", m, tk), c.p)
			run.Set(fmt.Sprintf("recall_embed_m%d_t%d_recall", m, tk), c.r)
			run.Set(fmt.Sprintf("recall_embed_m%d_t%d_f1", m, tk), c.f)
		}
	}

	logCalibMatrix(t, "EMBEDDING RECALL", embedThresholds, results,
		func(c calibCell) float64 { return c.r })
	logCalibMatrix(t, "EMBEDDING PRECISION", embedThresholds, results,
		func(c calibCell) float64 { return c.p })

	mPath := filepath.Join(t.TempDir(), "recall-fidelity-embedding.metrics.json")
	if err := run.WriteJSON(mPath); err != nil {
		t.Errorf("metrics write: %v", err)
	}
	t.Logf("metrics blob: %s", mPath)
}
