#!/usr/bin/env python3
"""Embedding generator for the recall-fidelity embedding sweep (Phase C.6+).

Calls the `reaper` provider's OpenAI-compatible /v1/embeddings endpoint
to embed (a) each corpus topic's article text — the stored substrate —
and (b) every mad-libs corpus query string. Writes a single
embeddings.json the Go embedding-recall test consumes.

This is the embedding counterpart of the symbolic recall measurement:
the C.6 calibration sweep showed symbolic Jaccard recall collapsing to
~10% under synonym drift; this artifact lets the same corpus be scored
with cosine similarity over `nomicai-embed` vectors, head to head.

embeddings.json is a DERIVED artifact — .gitignore'd, regenerated by
`make recall-embed-data`. It is deterministic given the pinned model,
so it is regenerable, not committed (same discipline as
corpus_queries.json).

Stdlib only (CONVENTIONS.md auxiliary-script constraint): urllib for HTTP.
`reaper` is local and non-metered; the API key is the placeholder
`dummy`.

Stored side = article text (truncated to the model's context), not the
5-anchor set: embeddings need real text, and the article is the
realistic thread substrate. nomic task prefixes (search_document: /
search_query:) are applied — standard for nomic-embed.
"""

import argparse
import json
import pathlib
import re
import sys
import time
import urllib.error
import urllib.request

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
MADLIBS_DATA = REPO_ROOT / "internal" / "scenarios" / "testdata" / "recall_madlibs"
CORPUS_JSON = REPO_ROOT / "internal" / "scenarios" / "testdata" / "corpus" / "corpus.json"
DEFAULT_OUT = MADLIBS_DATA / "embeddings.json"

DEFAULT_ENDPOINT = "http://reaper.local:4000/v1/embeddings"
DEFAULT_MODEL = "nomicai-embed"
DEFAULT_MAX_CHARS = 28000  # keep article text within the model context
BATCH = 32


def slug(title):
    """Slug matching the topic naming used by the corpus templates."""
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


def embed_batch(endpoint, model, texts, retries=2):
    """POST one batch of texts to the embeddings endpoint; return vectors."""
    body = json.dumps({"model": model, "input": texts}).encode("utf-8")
    req = urllib.request.Request(
        endpoint,
        data=body,
        headers={
            "Content-Type": "application/json",
            "Authorization": "Bearer dummy",
        },
    )
    for attempt in range(retries + 1):
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
            data = sorted(payload["data"], key=lambda d: d["index"])
            return [d["embedding"] for d in data]
        except (urllib.error.URLError, TimeoutError, KeyError, json.JSONDecodeError) as exc:
            if attempt < retries:
                time.sleep(2)
                continue
            raise RuntimeError(f"embeddings request failed: {exc}") from exc


def embed_all(endpoint, model, items, prefix):
    """Embed a list of (key, text) pairs; return {key: vector}."""
    out = {}
    keys = [k for k, _ in items]
    texts = [prefix + t for _, t in items]
    for i in range(0, len(texts), BATCH):
        batch = texts[i : i + BATCH]
        vecs = embed_batch(endpoint, model, batch)
        for k, v in zip(keys[i : i + BATCH], vecs):
            out[k] = v
        print(f"  embedded {min(i + BATCH, len(texts))}/{len(texts)}")
    return out


def load_topic_texts(max_chars):
    """Map topic name (wiki-<slug>) → truncated article text."""
    doc = json.loads(CORPUS_JSON.read_text(encoding="utf-8"))
    out = {}
    for art in doc["articles"]:
        name = "wiki-" + slug(art["title"])
        text = "\n\n".join(f["text"] for f in art["fragments"])
        out[name] = text[:max_chars]
    return out


def load_query_texts():
    """Collect every distinct corpus query string across the m-files.

    The `#` hashtag markers are stripped — they are an artifact of the
    symbolic mad-libs mechanism; an embedding query is the plain
    sentence.
    """
    texts = {}
    for path in sorted(MADLIBS_DATA.glob("corpus_queries_m*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        for q in doc["queries"]:
            s = q["user_input"].replace("#", "")
            texts[s] = s
    return texts


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT)
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    parser.add_argument("--max-chars", type=int, default=DEFAULT_MAX_CHARS)
    parser.add_argument(
        "--no-prefix",
        action="store_true",
        help="skip nomic search_query:/search_document: task prefixes",
    )
    args = parser.parse_args(argv)

    if not CORPUS_JSON.exists():
        print(f"corpus not found: {CORPUS_JSON}", file=sys.stderr)
        return 1
    query_texts = load_query_texts()
    if not query_texts:
        print("no corpus_queries_m*.json found — run `make recall-corpus-sweep-data`", file=sys.stderr)
        return 1

    doc_prefix = "" if args.no_prefix else "search_document: "
    qry_prefix = "" if args.no_prefix else "search_query: "

    topic_texts = load_topic_texts(args.max_chars)
    print(f"embedding {len(topic_texts)} topic article texts ...")
    topics = embed_all(args.endpoint, args.model, sorted(topic_texts.items()), doc_prefix)

    print(f"embedding {len(query_texts)} distinct query strings ...")
    queries = embed_all(args.endpoint, args.model, sorted(query_texts.items()), qry_prefix)

    dim = len(next(iter(topics.values())))
    doc = {
        "_comment": "DERIVED ARTIFACT - generated by embed_corpus.py; do not "
        "edit; not committed (see .gitignore). Regenerate: `make recall-embed-data`.",
        "model": args.model,
        "dim": dim,
        "task_prefixes": not args.no_prefix,
        "topics": topics,
        "queries": queries,
    }
    args.out.write_text(json.dumps(doc, sort_keys=True) + "\n", encoding="utf-8")
    print(
        f"wrote {args.out} - {len(topics)} topic vectors, "
        f"{len(queries)} query vectors, dim {dim}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
